### ISSUE TITLE
Customer in order list view

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/streamline-delivery#10]
Is it really useful to have the customer column in the order list view? Or is it enough to see it on the order details view?

**Comment by beatrizsavinhas** [comment]
The consensus from production was that it could be useful. But in order to reduce visual clutter, if the information is stated in the detail view (and in the future we can filter for customer when searching), I don't think this is a priority to add.

**Comment by seallard** [comment]
Yes, we want the customer in the order list view 👍
