### ISSUE TITLE
Delivery message endpoint for set of cases

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/streamline-delivery#17]
Add endpoint `/delivery_message?[]case_id=[...]` (or analysis id:s) which generates delivery message for a collection of cases.

- Validate that all analyses belong to the same order
- Validate that all analyses are completed
- Validate that all uploads are completed

**Comment by islean** [comment]
Implementation suggestions:

- Scrap old endpoint (sync with CiGRID) and use the new even for one case only
- We should validate
    - All cases should belong to the same order
    - All cases should have an analysis in the cg analysis table
- Response should have same structure as the one-case-endpoint, i.e.
```json
{
   message: "delivery message dependent on delivery method"
}
```
- Response should give a 400 bad request if the cases fail validation.
