### ISSUE TITLE
Associate old analyses with order

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/streamline-delivery#21]

**Comment by seallard** [comment]
For old analyses with existing tickets:
```sql
UPDATE `trailblazer-stage`.analysis a
JOIN `cg-stage`.order o ON a.ticket_id = o.ticket_id
SET a.order_id = o.id;
```

**Comment by seallard** [comment]
For old analyses without tickets, it is necessary to go via the ticket set on the case. This in turn relies on us having associated all cases with their orders.

**Comment by islean** [comment]
Nice! Seems good to me! We will need to fix analyses tied to cases with more than one ticket and for analyses without ticket_id as you mentioned but this is a good start!

**Comment by Vince-janv** [comment]
The provided script looks good 👍  Probably nice to do the other analyses separately as you suggest

**Comment by islean** [comment]
Would we want to run this now or after new analyses gets tagged with the order_id @seallard @Vince-janv ?

**Comment by islean** [comment]
New analyses should get their order_id set now. Should we aim for running the script soon? @seallard @Vince-janv

**Comment by seallard** [comment]
Lets do it! 🥳

**Comment by seallard** [comment]
Ran in prod
```
Updated Rows	50149
Query	UPDATE `trailblazer`.analysis a
	JOIN `cg`.order o ON a.ticket_id = o.ticket_id
	SET a.order_id = o.id
Start time	Tue Feb 27 14:12:15 CET 2024
Finish time	Tue Feb 27 14:12:18 CET 2024
```
