### ISSUE TITLE
Create orders for all tickets in status db

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/streamline-delivery#41]
The previous [script](https://github.com/Clinical-Genomics/cg/issues/2887) we ran only created orders for the most recent tickets on cases. We need to create orders for all of them since some analyses are uniquely mapped against these tickets.

**Comment by seallard** [comment]
Reusing the old script
```python
status_db = Store()

all_cases: list[Case] = status_db.get_cases()
print(len(all_cases))
for case in all_cases:
    ticket_id: str = case.latest_ticket
    if ticket_id:
        if status_db._get_query(table=Order).filter(Order.ticket_id == ticket_id).first():
            continue
        new_order = Order(workflow=case.data_analysis, customer_id=case.customer_id, order_date=case.ordered_at.date())
        status_db.session.add(new_order)

status_db.session.commit()
```

**Comment by islean** [comment]
Might be quicker to filter on tickets containing "," when getting the cases? Might not be worth it though, there are not too many cases. Might also be easier to just keep an int as "created_orders" instead of keeping all created orders in memory. Should work though 💪

**Comment by seallard** [comment]
Output in production:
```
Found 249 cases with multiple tickets.
Found 13 tickets without an order
Tickets without an order: ['968144', '948757', '626993', '926356', '372339', '449156', '631202', '797047', '463354', '230366', '552937', '578312', '601596']
Created 13 orders.
```
