### ISSUE TITLE
Debug cases associated with the wrong order

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/streamline-delivery#43]
It seems like we have cases associated with orders but where the ticket on the case does not match the ticket on the order.

Two such cases exist, `raretiger` and `promptmite`.

**Comment by seallard** [comment]
The `promptmite` case has ticket `294988`.
It is associated with these two orders
| order      | customer id | order date         | ticket  | workflow   |
|------|----------|-----------------------|--------|--------|
| 815  | 4        | 2017-09-26 00:00:00   | 294988 | mip-dna|
| 9531 | 3        | 2024-02-21 10:58:08   | 980419 | fastq  |

**Comment by seallard** [comment]
The `raretiger` case has ticket `338552`. It is associated with these two orders
| order      | customer id | order date         | ticket  | workflow   |
|------|----------|-----------------------|--------|--------|
| 814  | 4        | 2017-09-26 00:00:00   | 338552 | mip-dna |
| 9521 | 34       | 2024-02-21 10:58:08   | 748502 | fluffy  |

**Comment by seallard** [comment]
Diagnosis: the records used here https://github.com/Clinical-Genomics/cg/pull/2952/files#diff-674e8ccb46543502293e981bae90e10ecf950edfb7ca5b3c3c59ad456462143aR139 are not necessarily `case` records. So we used the wrong database id:s.

**Comment by islean** [comment]
Completed by using ticket_id to identify cases upon order submission.
