### ISSUE TITLE
Associate old analyses without tickets with ticket

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/streamline-delivery#44]
Many (30 000) analyses do not have a ticket id set.
Since we have created a case-order table, we can potentially update some of them with their correct ticket like
```
analysis.case_id -> case -> case.orders -> order -> order.id -> order.ticket
```
This will also allow us to associate them with their order id.

**Comment by seallard** [comment]
Suggestion

```SQL
UPDATE `trailblazer-stage`.analysis
SET ticket_id = (
    SELECT o.ticket_id
    FROM `cg-stage`.`order` o
    INNER JOIN `cg-stage`.case_order co ON o.id = co.order_id
    INNER JOIN `cg-stage`.`case` c ON co.case_id = c.id
    WHERE c.id = `trailblazer-stage`.analysis.case_id
    ORDER BY o.order_date DESC
    LIMIT 1
)
WHERE ticket_id IS NULL;
```

**Comment by Vince-janv** [comment]
Looks great 👍 Nice description in the first comment. Have we tested this in stage?

**Comment by islean** [comment]
There is a typo in 
INNER JOIN `cg-stage`.order_case oc ON o.id = co.order_id
where it should be oc.order_id.

**Comment by islean** [comment]
Also - will there be some typing issue? Even though we limit to 1 in the SELECT query, will there be a clash where [ticket_id] != ticket_id?

**Comment by seallard** [comment]
> Looks great 👍 Nice description in the first comment. Have we tested this in stage?

I ran a select query version of it which works
```SQL
SELECT COUNT(*) AS records_to_be_updated
FROM `trailblazer-stage`.analysis a
WHERE a.ticket_id IS NULL
AND EXISTS (
    SELECT 1
    FROM `cg-stage`.`order` o
    INNER JOIN `cg-stage`.order_case oc ON o.id = oc.order_id
    INNER JOIN `cg-stage`.`case` c ON oc.case_id = c.id
    WHERE c.internal_id = a.case_id
    ORDER BY o.order_date DESC
    LIMIT 1
);
```

27273 records will be updated.

**Comment by seallard** [comment]
> Looks great 👍 Nice description in the first comment. Have we tested this in stage?

I tested running it in stage
```
Updated Rows	30574
Query	UPDATE `trailblazer-stage`.analysis
	SET ticket_id = (
	    SELECT o.ticket_id
	    FROM `cg-stage`.`order` o
	    INNER JOIN `cg-stage`.order_case oc ON o.id = oc.order_id
	    INNER JOIN `cg-stage`.`case` c ON oc.case_id = c.id
	    WHERE c.internal_id = `trailblazer-stage`.analysis.case_id
	    ORDER BY o.order_date DESC
	    LIMIT 1
	)
	WHERE ticket_id IS NULL
Start time	Tue Feb 27 11:32:05 CET 2024
Finish time	Tue Feb 27 11:32:06 CET 2024
```

**Comment by seallard** [comment]
> Beautiful 🥳 Can we run a check how many analyses in trailblazer-stage have an order_id matching with an order with a different ticket_id than the analysis? To see if there were any errors?

The order ids have not been set, but will check via analysis -> case -> order -> ticket

**Comment by islean** [comment]
Oh right, got it confused!

**Comment by seallard** [comment]
I ran this query to find any mismatches
```SQL
SELECT 
    COUNT(*) AS mismatch_count
FROM (
    SELECT 
        a.id AS analysis_id,
        a.ticket_id AS updated_ticket_id,
        (
            SELECT o.ticket_id
            FROM `cg-stage`.`order` o
            INNER JOIN `cg-stage`.order_case oc ON o.id = oc.order_id
            INNER JOIN `cg-stage`.`case` c ON oc.case_id = c.id
            WHERE c.internal_id = a.case_id
            ORDER BY o.order_date DESC
            LIMIT 1
        ) AS expected_ticket_id
    FROM 
        `trailblazer-stage`.analysis a
    WHERE 
        a.ticket_id IS NOT NULL
) AS subquery
WHERE subquery.updated_ticket_id != subquery.expected_ticket_id;
```
Which returns 219 matches. However, the same query in production returns 220 matches. So I do not think that this query introduced the inconsistency.

Looking at the mismatching analysis -> order tickets:

| analysis_id | updated_ticket_id | expected_ticket_id |
|-------------|-------------------|--------------------|
| 265973      | 278868            | 711399             |
| 266003      | 210942            | 834795             |
| 267089      | 926849            | 258677             |
| 267587      | 926849            | 258677             |
| 267857      | 109760            | 913385             |
| 267881      | 109760            | 980812             |

**Comment by seallard** [comment]
I associated all analyses in stage with their order as well using
```SQL
UPDATE `trailblazer-stage`.analysis a
JOIN `cg-stage`.order o ON a.ticket_id = o.ticket_id
SET a.order_id = o.id;
```

And then ran this query to check that the ticket on each analysis matches the one on its order
```SQL
SELECT COUNT(*) AS mismatch_count
FROM `trailblazer-stage`.analysis a
INNER JOIN `cg-stage`.`order_case` oc ON a.order_id = oc.order_id
INNER JOIN `cg-stage`.`order` o ON oc.order_id = o.id
WHERE a.ticket_id != o.ticket_id AND a.order_id IS NOT NULL;
```
And there are no mismatches in stage.

**Comment by seallard** [comment]
Ran in prod 
```
Updated Rows	30600
Query	UPDATE `trailblazer`.analysis
	SET ticket_id = (
	    SELECT o.ticket_id
	    FROM `cg`.`order` o
	    INNER JOIN `cg`.order_case oc ON o.id = oc.order_id
	    INNER JOIN `cg`.`case` c ON oc.case_id = c.id
	    WHERE c.internal_id = `trailblazer`.analysis.case_id
	    ORDER BY o.order_date DESC
	    LIMIT 1
	)
	WHERE ticket_id IS NULL
Start time	Tue Feb 27 14:10:57 CET 2024
Finish time	Tue Feb 27 14:10:58 CET 2024
```
