### ISSUE TITLE
How to count analyses

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/streamline-delivery#53]
Currently we see some discrepancies in analyses summaries which I think are due to several things.

1. Seems as if failed analyses which have been restarted are marked as hidden. Should we exclude all hidden analyses in the status summary?
2. Take https://cigrid.scilifelab.se/orders/9357. We have 6 cases in statusdb, we have 6 completed analyses. Yet 4 cases are under lab-prep. How come? Several samples are downsampled, might be the reason? How are last_sequenced_at and prepared_at set for such samples?
3. Take https://cigrid.scilifelab.se/orders/9363. This has one case, which has been delivered. All samples seem to have last_sequenced_at but no prepared_at. Why? https://cg-statusdb.scilifelab.se/admin/sample/?search=ACC13854
4. Take https://cigrid.scilifelab.se/orders/9370. This has one case in total but we set delivered to 2. This seems to be since its rsync "analysis" has the same order_id. Should it be like this or do we have a problem with how we tag analyses with order_ids? Right now we do not show RSYNC analyses under an order since we filter on workflow. Should this be changed?

**Comment by seallard** [comment]
👍  Also, is a summary based on sample better? Seems strange since production deals in analyses though. If so what does each status mean when applied to the samples?

**Comment by vwirta** [comment]
Great to start this discussion.
I'll provide some input here... 

For us it is relevant to capture statistics both related to i) number of samples and ii) number of analyses.

i) Number of samples is relevant as invoicing is based on this and this provides the best measure of our efforts in the lab.

ii) Number of analyses is something I have always been interested to have an insight into, but this has not been possible. This number is relevant to relate to number of samples (for example, how many analyses do we do per sample?) and put a number on the efforts done in prod bioinfo. Also, we can use this number to relate to our HPC and storage usage, which would be very welcome to help in pricing these parts of our services.

In all stats, I would like to remove samples from cust000 and all cust9xxx numbers as these are some type of internal samples that we do not invoice.

**Comment by seallard** [comment]
We can definitely expand the scope of the `OrderStatusService` (or implement another service) with functionality to provide trending for business purposes as well at some point.

**Comment by ChrOertlin** [comment]
> What do we do with these: https://cigrid.scilifelab.se/orders/4? Seems as if failed analyses were set to completed either way?

Sometimes analysis fail due to PCT_ADAPTERS or other metrics that are above a certain set threshold. Even though they are above the threshold it is unlikely that it will impact the analysis negatively. Right now these cases will be set to Failed but then a production team member can set them to completed and deliver the case /analysis.

regarding your second point and downsampling:
The downsample api just copies relevant information from the origninal case and samples. If there are certain design changes that warrants adjustment of certain attributes we likely need to also change that in the downsample api

**Comment by islean** [comment]
For context; our first aim is to realize this mock although statistics are certainly a possibility moving forwards:

<img width="803" alt="image" src="https://github.com/Clinical-Genomics/streamline-delivery/assets/40887124/1528b564-e90c-43f7-a41f-f68c52e0b37f">

**Comment by Vince-janv** [comment]
> Currently we see some discrepancies in analyses summaries which I think are due to several things.
> 
> 1. Seems as if failed analyses which have been restarted are marked as hidden. Should we exclude all hidden analyses in the status summary?
> 2. Take [cigrid.scilifelab.se/orders/9357](https://cigrid.scilifelab.se/orders/9357). We have 6 cases in statusdb, we have 6 completed analyses. Yet 4 cases are under lab-prep. How come? Several samples are downsampled, might be the reason? How are last_sequenced_at and prepared_at set for such samples?
> 3. Take [cigrid.scilifelab.se/orders/9363](https://cigrid.scilifelab.se/orders/9363). This has one case, which has been delivered. All samples seem to have last_sequenced_at but no prepared_at. Why? [cg-statusdb.scilifelab.se/admin/sample/?search=ACC13854](https://cg-statusdb.scilifelab.se/admin/sample/?search=ACC13854)
> 4. Take [cigrid.scilifelab.se/orders/9370](https://cigrid.scilifelab.se/orders/9370). This has one case in total but we set delivered to 2. This seems to be since its rsync "analysis" has the same order_id. Should it be like this or do we have a problem with how we tag analyses with order_ids? Right now we do not show RSYNC analyses under an order since we filter on workflow. Should this be changed?

1. Not sure what you mean here could you elaborate @islean?
2. Yes downsampling is likely the issue. As for now, we only downsample samples in internal validations, ie cases production want to hide anyway.
3. Not all workflows in LIMS (preps) set the timestamps we want. We should identify these and create issues for the LIMS-developers to implement (should be quite easy I'm told).
4. No, I consider this a bug. We should change it.

**Comment by seallard** [comment]
Context for 4 @islean: since we have not implemented the `delivered` functionality yet, the `delivered` status actually means completed currently. It is just a placeholder

**Comment by islean** [comment]
> > Currently we see some discrepancies in analyses summaries which I think are due to several things.
> > 
> > 1. Seems as if failed analyses which have been restarted are marked as hidden. Should we exclude all hidden analyses in the status summary?
> > 2. Take [cigrid.scilifelab.se/orders/9357](https://cigrid.scilifelab.se/orders/9357). We have 6 cases in statusdb, we have 6 completed analyses. Yet 4 cases are under lab-prep. How come? Several samples are downsampled, might be the reason? How are last_sequenced_at and prepared_at set for such samples?
> > 3. Take [cigrid.scilifelab.se/orders/9363](https://cigrid.scilifelab.se/orders/9363). This has one case, which has been delivered. All samples seem to have last_sequenced_at but no prepared_at. Why? [cg-statusdb.scilifelab.se/admin/sample/?search=ACC13854](https://cg-statusdb.scilifelab.se/admin/sample/?search=ACC13854)
> > 4. Take [cigrid.scilifelab.se/orders/9370](https://cigrid.scilifelab.se/orders/9370). This has one case in total but we set delivered to 2. This seems to be since its rsync "analysis" has the same order_id. Should it be like this or do we have a problem with how we tag analyses with order_ids? Right now we do not show RSYNC analyses under an order since we filter on workflow. Should this be changed?
> 
>     1. Not sure what you mean here could you elaborate @islean?
> 
>     2. Yes downsampling is likely the issue. As for now, we only downsample samples in internal validations, ie cases production want to hide anyway.
> 
>     3. Not all workflows in LIMS (preps) set the timestamps we want. We should identify these and create issues for the LIMS-developers to implement (should be quite easy I'm told).
> 
>     4. No, I consider this a bug. We should change it.

1. Well, when an analysis fails and is re-run, the old analysis is marked as failed and in some cases is marked as "hidden". They will not show up in the list of analyses. The failed analyses are counted in the status summary though, meaning that the total does not equal the sum of the parts. See https://cigrid.scilifelab.se/orders/9474 for example

**Comment by Vince-janv** [comment]
> 1. Well, when an analysis fails and is re-run, the old analysis is marked as failed and in some cases is marked as "hidden". They will not show up in the list of analyses. The failed analyses are counted in the status summary though, meaning that the total does not equal the sum of the parts. See [cigrid.scilifelab.se/orders/9474](https://cigrid.scilifelab.se/orders/9474) for example

Our goal is to show one status per case, so I think this should be patched. I suggest we use the status of the latest_analysis

**Comment by islean** [comment]
> Context for 4 @islean: since we have not implemented the `delivered` functionality yet, the `delivered` status actually means completed currently. It is just a placeholder

Regardless if it counts as delivered or completed, we would still end up with more analyses than the total though.

**Comment by vwirta** [comment]
> 3\. Take [cigrid.scilifelab.se/orders/9363](https://cigrid.scilifelab.se/orders/9363). This has one case, which has been delivered. All samples seem to have last_sequenced_at but no prepared_at. Why? [cg-statusdb.scilifelab.se/admin/sample/?search=ACC13854](https://cg-statusdb.scilifelab.se/admin/sample/?search=ACC13854)

This is a RML order where the libraries have been prepared by the customer, which is the reason they lack the prepared_at date

**Comment by beatrizsavinhas** [comment]
> What do we do with these: [cigrid.scilifelab.se/orders/4](https://cigrid.scilifelab.se/orders/4)? Seems as if failed analyses were set to completed either way?

The 2 most recent analyses are reruns of the original case from 2021. However all analyses have the same ticket id from 2024. This is a result of the patch which set the latest ticket id to analyses in TB that did not have a ticket id set. We can just disregard these I think.

**Comment by beatrizsavinhas** [comment]
1. We should disregard hidden analyses in the stats. Agree with:

> Our goal is to show one status per case, so I think this should be patched. I suggest we use the status of the latest_analysis


2. Should we make an exception for downsampled samples? Setting a dummy date for last_sequenced_at and prepared_at in StatusDB would be incorrect for these samples.
3. Agree with this:

> 3. Seems reasonable to disregard a missing prepared_at if last_sequenced_at has been set

4. We should disregard RSYNC analyses (it is part of this project to not have these as "analysis" even). Agree with:

> 4. No, I consider this a bug. We should change it.
