### ISSUE TITLE
Add button for generating delivery message for an order in the detailed order view

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/streamline-delivery#62]
Should be in the detailed order view. Probably not needed in the list view since they can not reach the susy ticket from there either way. 

- Button should say "Get delivery message" as in the mock.
- Always render, though only completed cases will be included.
- Should send GET to /orders/<order_id>/delivery_message
- Response described in https://github.com/Clinical-Genomics/streamline-delivery/issues/16, i.e.
- Response will follow same design as for one case, i.e.
```json
{
    message: "delivery message dependent on delivery method"
}
```
- Response will give a 400 bad request error if there are if the order can not be found.

**Comment by moedarrah** [comment]
Done!
