### ISSUE TITLE
Mark old analyses as delivered

### ISSUE THREAD

**Issue by islean** [Clinical-Genomics/streamline-delivery#79]
Since the filtering on delivered/not delivered analyses should reflect whether actions are required, we should mark old analyses as delivered.

Suggested criteria:
- Older than 2 months (and completed), set as delivered
- Newer than 2 months and fulfilling the following:
    - All associated samples have a delivered_at date in status_db
    - The analysis should have a comment

Problem:
What user and date should be set for the delivery? Should they be left empty and we let the columns be nullable? New analyses will have those values filled in either way. Otherwise a dummy user would show misleading values upon hover. 

Production will cover outliers not covered by the agreed criteria.

**Comment by islean** [comment]
Suggested script for marking analyses older than 2 months (should discuss dummy user):

```
store = Store()
session = get_session()

hiseq_user = store.get_user(email="HASTA-REST")

analyses_more_than_8_weeks_old: list[Analysis] = session.query(Analysis)\
    .filter(Analysis.started_at < datetime.datetime.today() - datetime.timedelta(weeks=8))\
    .filter(Analysis.status == TrailblazerStatus.COMPLETED)\
    .all()



for analysis in analyses_more_than_8_weeks_old:
    delivery = Delivery(
        analysis_id=analysis.id,
        delivered_by=hiseq_user.id,
        delivered_date=datetime.datetime.today()
    )
    session.add(delivery)

session.commit()
```

**Comment by islean** [comment]
Suggested query for getting tickets with newer analyses which should potentially be marked as delivered:

```Python
ticket_ids_for_analyses_newer_than_8_weeks: list[int] = session.query(Analysis.ticket_id)\
    .filter(Analysis.started_at >= datetime.datetime.today() - datetime.timedelta(weeks=8))\
    .filter(Analysis.status == TrailblazerStatus.COMPLETED)\
    .filter(Analysis.comment)\
    .all()
```

**Comment by islean** [comment]
Suggested marking of selected "newer" analyses:

```Python
store = Store()
session = get_session()

hiseq_user = store.get_user(email="hiseq.clinical@scilifelab.se")

file = open('/Users/isakohlsson/Documents/analysis_ids_to_mark_as_delivered.txt', 'w')

for analysis_id in file.readlines():
    delivery = Delivery(
        analysis_id=int(analysis_id),
        delivered_by=hiseq_user.id,
        delivered_date=datetime.datetime.today()
    )
    session.add(delivery)

session.commit()
```

**Comment by seallard** [comment]
Looks good 👍  Maybe we should set the delivery date to the analysis upload date

**Comment by islean** [comment]
@seallard I guess that depends on what we want. Given that I don't think the data should be considered trustworthy either way, and that people should look at the comment for these older analyses, either way works for me. I do not see much gain from it though.

**Comment by islean** [comment]
Ran in production. There are 91 analyses which are completed, visible, not rsync nor demultiplex and which are not delivered.
