### ISSUE TITLE
Order summary implementation plan

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/streamline-delivery#80]
The functionality will be exposed via `/orders` and `/orders/<order_id>`. These endpoints will 
- Calculate the total case count in the order.
- Collect a summary of the cases in the order based on the samples.
- Collect a summary of the cases in the order based on the analyses in trailblazer.

## Implementation suggestion
Since the creation of summaries need to be fast, use count queries to the largest extent possible. It is faster than retrieving a bunch of records and iterating over them.

### Analysis summary
To make the analyses summary meaningful we need to
- (Remove creation of) disregard rsync analyses.
- Only consider the most recent analysis for a case.
- Ensure the `/summary` endpoint is fast.

The above points are fairly straightforward. Identify the analysis statuses in the following way
- Running: analysis has status running
- Completed: analysis has status completed
- Failed: analysis has status failed
- Uploaded: analysis has `upload_date` set
- Upload failed: ?
- Analysis has a `Delivery` entry

### Case summary
Identify the case statuses in the following way
- Cases which have not been received: any sample in the case lacks `received_at`
- Cases which are being prepared in the lab: all samples in the case have been received but not all of them have `prepared_at` set.
- Cases which are being sequenced: all samples have been prepared but not all have `sequenced_at` set.
- Cases being demultiplexed: all samples have been sequenced but not all have ?

Some samples are externally sequenced, meaning they will not be prepared in the lab. Adjust the logic accordingly.

### Questions regarding implementation plan
- Can we stop creating rsync analyses?
- How can we identify cases in demultiplexing?
- When is the `sequenced_at` date set on a sample?

#### Removing rsync analyses
Can we stop creating rsync analyses already? We do track them as upload jobs, but is there any logic which relies on the rsync analyses existing that we need to refactor first? At a minimum we need to
- Remove rsync tab in cigrid
- Remove rsync analysis creation in cg

And also potentially (not urgent - just to avoid technical debt)
- Remove old rsync analyses
- Remove rsync as a valid workflow option in trailblazer and cg

Currently, we only associate the upload job with the rsync analysis. To remove rsync analyses we need to associate the job with the corresponding analysis directly.

#### Identifying cases in demultiplexing
It is not clear to me how we currently identify cases in demultiplexing or what, if any, new logic needs to be added to enable us to identify cases being demultiplexed.

**Comment by islean** [comment]
We are missing excluding hidden analyses from the count. I guess that should be included?

Also - does this cover downsampled cases and RML?

**Comment by beatrizsavinhas** [comment]
RML still go through some lab steps so effectively they would work as any other sample.

Downsampled (Good point!) samples skip the lab, sequencing and demultiplexing steps as they go straight to the analysis.
