### ISSUE TITLE
Investigate potential bugs with total count not adding up

### ISSUE THREAD

**Issue by seallard** [Clinical-Genomics/streamline-delivery#89]
For example order 9824 with 20 total and 19 delivered.

**Comment by islean** [comment]
Other examples:

https://cigrid.scilifelab.se/orders/9811 has 10 cases, but only 8 reported as delivered. Two are missing. Seems as if the samples have no entries in Housekeeper (see ACC14218A5).

**Comment by islean** [comment]
Topups are not displayed properly

**Comment by islean** [comment]
Investigation done for now, only topups identified as issue.
